# Generated by Django 6.1.1 on 2026-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Se usa en la URL. Ej: 'proyectos' produce #proyectos", unique=True, verbose_name='Identificador')),
                ('kind', models.CharField(choices=[('hero', 'Portada'), ('text', 'Texto'), ('skills', 'Stack tecnológico'), ('projects', 'Proyectos'), ('contact', 'Contacto')], max_length=20, verbose_name='Tipo')),
                ('nav_label', models.CharField(max_length=40, verbose_name='Etiqueta del menú')),
                ('heading', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('role', models.CharField(max_length=120, verbose_name='Rol')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Perfil del sitio',
                'verbose_name_plural': 'Perfil del sitio',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, verbose_name='Enlace')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repositorio')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
    ]
