# Generated by Django 6.1.1 on 2026-09-22 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG o PNG cuadrado. Recomendado: SVG.', null=True, upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp', 'jpg', 'jpeg'])], verbose_name='Icono'),
        ),
    ]
