# Generated by Django 6.1.1 on 2026-09-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='github',
            field=models.URLField(blank=True, help_text='Ej: https://github.com/usuario', verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número con prefijo de país, sin espacios. Ej: +34600111222', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
